driver:
  server:
    port: 30000
    so-timeout: 300000
    so-receive-buffer-size: 160
    so-send-buffer-size: 160

logging:
  level:
    root: INFO
    com.netflix.discovery: 'WARN'
    org.openwms: 'DEBUG'
    org.dozer: 'ERROR'
    CORE_INTEGRATION_MESSAGING: 'DEBUG'